project_id = "mityzsdqonwfhlahvkiw"

[functions.notify-submission]
verify_jwt = true

[functions.generate-palette]
verify_jwt = true

[functions.generate-logo]
verify_jwt = true

[functions.design-locked]
verify_jwt = true

[functions.prospect-submitted]
verify_jwt = false

[functions.convert-prospect-to-client]
verify_jwt = true

[functions.invite-am]
verify_jwt = true

[functions.generate-landing-pages]
verify_jwt = false
