import { createFileRoute, useNavigate, useParams } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import {
  ArrowRight,
  Eye,
  Image as ImageIcon,
  MessageSquare,
  Palette,
  Sparkles,
} from "lucide-react";
import { TriveltaLogo } from "@/components/TriveltaLogo";
import { useOnboardingCtx } from "@/lib/onboarding-context";
import { useAuth } from "@/lib/auth-context";

export const Route = createFileRoute("/onboarding/$clientId/studio-intro")({
  component: StudioIntro,
});

function skipKey(clientId: string) {
  return `studio-skip-intro-${clientId}`;
}

function StudioIntro() {
  const { clientId } = useParams({ from: "/onboarding/$clientId/studio-intro" });
  const navigate = useNavigate();
  const { welcomeInfo } = useOnboardingCtx();
  const { user, loading: authLoading } = useAuth();
  const [skipNextTime, setSkipNextTime] = useState(false);
  const [leaving, setLeaving] = useState(false);

  // Auth guard + auto-skip if previously opted out
  useEffect(() => {
    if (authLoading) return;
    if (!user) {
      navigate({ to: "/onboarding/$clientId/auth", params: { clientId }, replace: true });
      return;
    }
    try {
      if (localStorage.getItem(skipKey(clientId)) === "true") {
        navigate({
          to: "/onboarding/$clientId/studio",
          params: { clientId },
          search: { from: "intro" } as never,
          replace: true,
        });
      }
    } catch {
      /* localStorage unavailable — show intro */
    }
  }, [authLoading, user, clientId, navigate]);

  useEffect(() => {
    document.title = "Trivelta Studio · Welcome";
  }, []);

  const handleEnterStudio = () => {
    try {
      if (skipNextTime) localStorage.setItem(skipKey(clientId), "true");
      else localStorage.removeItem(skipKey(clientId));
    } catch {
      /* ignore */
    }
    setLeaving(true);
    setTimeout(() => {
      navigate({
        to: "/onboarding/$clientId/studio",
        params: { clientId },
        search: { from: "intro" } as never,
      });
    }, 220);
  };

  const features = [
    { icon: MessageSquare, label: "AI Chat", desc: "Describe your brand in plain English" },
    { icon: Palette, label: "344 Colors", desc: "Every detail, semantically aware" },
    { icon: ImageIcon, label: "Logo Studio", desc: "3 unique variants per request" },
    { icon: Eye, label: "Live Preview", desc: "See your platform instantly" },
  ];

  return (
    <div
      className={`relative min-h-screen flex items-center justify-center px-4 py-12 overflow-hidden transition-opacity duration-200 ${
        leaving ? "opacity-0" : "opacity-100 route-fade-in"
      }`}
    >
      {/* Animated background orbs */}
      <div className="pointer-events-none absolute inset-0" aria-hidden="true">
        <div className="orb-1 absolute left-[10%] top-[15%] h-[420px] w-[420px] rounded-full bg-primary opacity-[0.07] blur-[120px]" />
        <div className="orb-2 absolute right-[8%] bottom-[10%] h-[360px] w-[360px] rounded-full bg-primary opacity-[0.06] blur-[120px]" />
        <div className="orb-3 absolute left-[40%] top-[60%] h-[300px] w-[300px] rounded-full bg-primary opacity-[0.04] blur-[120px]" />
      </div>

      <div className="relative z-10 w-full max-w-2xl text-center">
        {/* Studio branding lockup */}
        <div className="mb-10 flex items-center justify-center">
          <TriveltaLogo size="md" product="Studio" />
        </div>

        {/* Personal welcome */}
        {welcomeInfo?.clientName && (
          <div className="mb-3 font-mono text-[11px] uppercase tracking-[0.22em] text-muted-foreground">
            Welcome, {welcomeInfo.clientName}
          </div>
        )}

        {/* Headline */}
        <h1 className="mb-4 text-4xl md:text-5xl font-bold text-foreground tracking-tight">
          Build your brand,
          <br />
          <span className="bg-gradient-to-r from-primary via-primary to-primary/60 bg-clip-text text-transparent">
            with AI
          </span>
        </h1>

        <p className="mx-auto mb-12 max-w-md text-base text-muted-foreground leading-relaxed">
          The complete design system for your iGaming platform — generated by AI, refined by you.
        </p>

        {/* Feature grid */}
        <div className="mb-12 grid grid-cols-2 md:grid-cols-4 gap-4">
          {features.map((feat, i) => (
            <div
              key={feat.label}
              className="rounded-xl border border-border/50 bg-card/40 p-4 backdrop-blur-sm transition-all hover:border-primary/40 hover:-translate-y-1 hover:bg-card/60"
              style={{ animationDelay: `${i * 90}ms` }}
            >
              <div className="mx-auto mb-3 grid h-9 w-9 place-items-center rounded-lg bg-primary/15 ring-1 ring-primary/20">
                <feat.icon className="h-4 w-4 text-primary" />
              </div>
              <div className="mb-1 text-xs font-semibold text-foreground">{feat.label}</div>
              <div className="text-[10px] leading-relaxed text-muted-foreground/80">
                {feat.desc}
              </div>
            </div>
          ))}
        </div>

        {/* CTA */}
        <button
          onClick={handleEnterStudio}
          className="group inline-flex items-center gap-2 rounded-xl bg-primary px-6 py-4 text-base font-semibold text-primary-foreground shadow-[0_14px_40px_-10px_color-mix(in_oklab,var(--color-primary)_55%,transparent)] transition-all hover:-translate-y-0.5 hover:shadow-[0_18px_50px_-10px_color-mix(in_oklab,var(--color-primary)_70%,transparent)]"
        >
          Enter Studio
          <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1" />
        </button>

        {/* Skip toggle */}
        <div className="mt-6">
          <label className="inline-flex items-center gap-2 text-[11px] text-muted-foreground/70 cursor-pointer hover:text-muted-foreground">
            <input
              type="checkbox"
              checked={skipNextTime}
              onChange={(e) => setSkipNextTime(e.target.checked)}
              className="rounded border-border accent-primary"
            />
            Skip this intro next time
          </label>
        </div>

        {/* Footer micro-label */}
        <div className="mt-10 inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.28em] text-muted-foreground/60">
          <Sparkles className="h-3 w-3" />
          AI-Powered Design Studio
        </div>
      </div>
    </div>
  );
}
