/**
 * TCM Strings — Trivelta Copy Model (SHARED MODULE — Deno/Edge Function copy)
 *
 * ⚠️  SYNC WARNING: This file is a verbatim copy of src/lib/tcm-strings.ts
 * for use inside Supabase Edge Functions (Deno runtime).
 * If you change src/lib/tcm-strings.ts, manually update this file too.
 */

export type Language = "en" | "fr" | "pt" | "sw" | "yo" | "ha" | "ar";

export interface TCMStrings {
  // ── App identity (injected dynamically; DO NOT translate) ─────────────────
  APP_NAME: string;
  CURRENCY_SYMBOL: string;
  CASH: string;
  // ── Navigation ──────────────────────────────────────────────────────────
  FEED: string;
  SPORTSBOOK: string;
  DISCOVERY: string;
  CASINO: string;
  SOCIAL_CASINO: string;
  PEER_TO_PEER_NAV: string;
  PEER_TO_PEER: string;
  HOME: string;
  PROFILE: string;
  // ── Quick access tiles ───────────────────────────────────────────────────
  TILE_LIVE_SPORTS: string;
  TILE_LOAD_CODE: string;
  TILE_VIRTUALS: string;
  TILE_PEER_TO_PEER: string;
  TILE_GAMERS_PARADISE: string;
  MOBILE_TILE_ALL_SPORTS: string;
  MOBILE_TILE_LIVE_SPO: string;
  MOBILE_TILE_LOAD_CO: string;
  MOBILE_TILE_GAMERS: string;
  // ── Buttons / actions ───────────────────────────────────────────────────
  BET_BUILDER: string;
  BETBUILDER: string;
  PEER_TO_PEER_BTN: string;
  PEER_TO_PEER_SHORT: string;
  SIGN_IN: string;
  CREATE_ACCOUNT: string;
  SEE_MORE: string;
  MORE_BETS: string;
  STATS: string;
  VIEW_TIPS: string;
  BACK_TO_SPORTS: string;
  SHARE: string;
  COLLAPSE: string;
  SHOW_ALL_LEGS: string;
  PLACE_A_BET: string;
  MAKE_BETS: string;
  // ── Welcome bonus ─────────────────────────────────────────────────────────
  WELCOME_BONUS: string;
  WELCOME_BONUS_PROMO: string;
  WELCOME_BONUS_BODY_WEB: string;
  WELCOME_BONUS_BODY_MOBILE: string;
  WELCOME_BONUS_SUBTITLE: string;
  // ── Section headings ──────────────────────────────────────────────────────
  LIVE_AND_UPCOMING: string;
  LIVE_AND_UPCOMING_GAMES: string;
  ALL_SPORTS: string;
  POPULAR: string;
  POPULAR_LEAGUES: string;
  DISCOVER: string;
  CASINO_HEADING: string;
  // ── Search ────────────────────────────────────────────────────────────────
  SEARCH: string;
  SEARCH_PLACEHOLDER: string;
  SEARCH_TEAMS_PLAYERS_EVENTS: string;
  // ── Tabs ──────────────────────────────────────────────────────────────────
  TAB_MY_BETS: string;
  MY_BETS: string;
  TAB_MY_FEED: string;
  MY_FEED: string;
  TAB_FRIENDS: string;
  TAB_EXPLORE: string;
  TAB_SPORTS: string;
  TAB_ALL_SPORTS: string;
  // ── Filters ───────────────────────────────────────────────────────────────
  FILTER_ALL: string;
  FILTER_PENDING: string;
  FILTER_SETTLED: string;
  FILTER_P2P: string;
  // ── Bet statuses ──────────────────────────────────────────────────────────
  STATUS_WON: string;
  STATUS_LOST: string;
  STATUS_PENDING: string;
  STATUS_LIVE: string;
  WON: string;
  LOST: string;
  PENDING: string;
  VOID: string;
  LIVE_TAG: string;
  SETTLED: string;
  // ── Bet labels ────────────────────────────────────────────────────────────
  STAKE: string;
  PAYOUT: string;
  POTENTIAL: string;
  OUTCOME: string;
  ODDS_LABEL: string;
  FLEX_CUTS: string;
  // ── Bet types ─────────────────────────────────────────────────────────────
  LEG_PARLAY: string;
  MONEYLINE: string;
  OVER_UNDER: string;
  SPREAD: string;
  BETSLIP_PARLAY_ODDS: string;
  // ── Betslip ───────────────────────────────────────────────────────────────
  BETSLIP: string;
  EMPTY_BET_SLIP_HEADING: string;
  EMPTY_BET_SLIP_DESCRIPTION: string;
  // ── Sport names ───────────────────────────────────────────────────────────
  SOCCER: string;
  BASKETBALL: string;
  TENNIS: string;
  TABLE_TENNIS: string;
  VOLLEYBALL: string;
  ICE_HOCKEY: string;
  AMERICAN_FOOTBALL: string;
  RUGBY: string;
  VIRTUAL: string;
  // ── Social ────────────────────────────────────────────────────────────────
  FOLLOWING: string;
  FOLLOWERS: string;
  REFER_FRIENDS: string;
  GET_BONUS_1: string;
  GET_BONUS_2: string;
  // ── Profile ───────────────────────────────────────────────────────────────
  WINS: string;
  TOTAL_BALANCE: string;
  AVAILABLE_TO_REDEEM: string;
  PURCHASE: string;
  PRIZE_REDEMPTION: string;
  TRANSACTION_HISTORY: string;
  AVAILABLE_BONUSES: string;
  TOP_5_CASINO_GAMES: string;
  // ── P2P ───────────────────────────────────────────────────────────────────
  PEER_TO_PEER_HEADING: string;
  PENDING_INVITES: string;
  CURRENT_BETS: string;
  PAST_BETS: string;
  HISTORY: string;
  // ── Misc ──────────────────────────────────────────────────────────────────
  NO_P2P_BETS: string;
  COMING_SOON: string;
  LIVE_BADGE: string;
}

export const DEFAULT_STRINGS: TCMStrings = {
  APP_NAME: "BetNova",
  CURRENCY_SYMBOL: "₦",
  CASH: "Naira",
  FEED: "Feed",
  SPORTSBOOK: "Sports",
  DISCOVERY: "Discovery",
  CASINO: "Casino",
  SOCIAL_CASINO: "Casino",
  PEER_TO_PEER_NAV: "Peer-to-peer",
  PEER_TO_PEER: "Peer-to-peer",
  HOME: "home",
  PROFILE: "Profile",
  TILE_LIVE_SPORTS: "Live Sports",
  TILE_LOAD_CODE: "Load Code",
  TILE_VIRTUALS: "Virtuals",
  TILE_PEER_TO_PEER: "Peer to Peer",
  TILE_GAMERS_PARADISE: "Gamers Paradise",
  MOBILE_TILE_ALL_SPORTS: "All Sports",
  MOBILE_TILE_LIVE_SPO: "Live Spo.",
  MOBILE_TILE_LOAD_CO: "Load Co.",
  MOBILE_TILE_GAMERS: "Gamers...",
  BET_BUILDER: "BetBuilder",
  BETBUILDER: "BetBuilder",
  PEER_TO_PEER_BTN: "Peer-to-Peer",
  PEER_TO_PEER_SHORT: "Peer-to-Peer",
  SIGN_IN: "Sign in",
  CREATE_ACCOUNT: "Create an account",
  SEE_MORE: "SEE MORE",
  MORE_BETS: "MORE BETS",
  STATS: "STATS",
  VIEW_TIPS: "View Tips",
  BACK_TO_SPORTS: "Back to Sports",
  SHARE: "Share",
  COLLAPSE: "Collapse",
  SHOW_ALL_LEGS: "Show all legs",
  PLACE_A_BET: "Place Bet",
  MAKE_BETS: "Make Bets",
  WELCOME_BONUS: "WELCOME BONUS",
  WELCOME_BONUS_PROMO: "GET A 100% BONUS ON YOUR FIRST DEPOSIT",
  WELCOME_BONUS_BODY_WEB:
    "Enjoy 100% welcome bonus on your first deposit and double your starting stake.",
  WELCOME_BONUS_BODY_MOBILE:
    "Get a Free Sportsbook Pick or Enjoy 50% More Casino Cash For Casino Games",
  WELCOME_BONUS_SUBTITLE:
    "Enjoy 100% welcome bonus on your first deposit and double your starting stake.",
  LIVE_AND_UPCOMING: "Live & Upcoming",
  LIVE_AND_UPCOMING_GAMES: "Live & Upcoming Games",
  ALL_SPORTS: "All Sports",
  POPULAR: "Popular",
  POPULAR_LEAGUES: "Popular Leagues",
  DISCOVER: "Discover",
  CASINO_HEADING: "Casino",
  SEARCH: "Search",
  SEARCH_PLACEHOLDER: "Search teams, players and events",
  SEARCH_TEAMS_PLAYERS_EVENTS: "Search teams, players and events",
  TAB_MY_BETS: "My Bets",
  MY_BETS: "My Bets",
  TAB_MY_FEED: "My Feed",
  MY_FEED: "My Feed",
  TAB_FRIENDS: "Friends",
  TAB_EXPLORE: "Explore",
  TAB_SPORTS: "Sports",
  TAB_ALL_SPORTS: "All Sports",
  FILTER_ALL: "All",
  FILTER_PENDING: "Pending",
  FILTER_SETTLED: "Settled",
  FILTER_P2P: "P2P",
  STATUS_WON: "WON",
  STATUS_LOST: "LOST",
  STATUS_PENDING: "PENDING",
  STATUS_LIVE: "LIVE",
  WON: "WON",
  LOST: "LOST",
  PENDING: "PENDING",
  VOID: "VOID",
  LIVE_TAG: "• Live",
  SETTLED: "Settled",
  STAKE: "STAKE",
  PAYOUT: "PAYOUT",
  POTENTIAL: "POTENTIAL",
  OUTCOME: "OUTCOME",
  ODDS_LABEL: "ODDS",
  FLEX_CUTS: "FLEX CUTS",
  LEG_PARLAY: "Selection Multi",
  MONEYLINE: "Match Winner",
  OVER_UNDER: "Over/Under",
  SPREAD: "Handicap",
  BETSLIP_PARLAY_ODDS: "Multi Odds",
  BETSLIP: "Betslip",
  EMPTY_BET_SLIP_HEADING: "Betslip is empty",
  EMPTY_BET_SLIP_DESCRIPTION: "Click on the odds to add to betslip",
  SOCCER: "Football",
  BASKETBALL: "Basketball",
  TENNIS: "Tennis",
  TABLE_TENNIS: "Table Tennis",
  VOLLEYBALL: "Volleyball",
  ICE_HOCKEY: "Ice Hockey",
  AMERICAN_FOOTBALL: "American Football",
  RUGBY: "Rugby",
  VIRTUAL: "Virtuals",
  FOLLOWING: "Following",
  FOLLOWERS: "Followers",
  REFER_FRIENDS: "Refer friends",
  GET_BONUS_1: "Refer your friends and build your social betting network",
  GET_BONUS_2: "Friend at a time",
  WINS: "Wins",
  TOTAL_BALANCE: "Total balance",
  AVAILABLE_TO_REDEEM: "Withdrawable Balance",
  PURCHASE: "Deposit",
  PRIZE_REDEMPTION: "Withdraw",
  TRANSACTION_HISTORY: "Transactions history",
  AVAILABLE_BONUSES: "Available Bonuses",
  TOP_5_CASINO_GAMES: "Top 5 Casino Games",
  PEER_TO_PEER_HEADING: "My peer-to-peer bets",
  PENDING_INVITES: "Pending invites",
  CURRENT_BETS: "Current bets",
  PAST_BETS: "Past bets",
  HISTORY: "History",
  NO_P2P_BETS: "No P2P bets yet",
  COMING_SOON: "Coming soon",
  LIVE_BADGE: "LIVE",
};

const FR_STRINGS: Partial<TCMStrings> = {
  CASH: "CFA",
  FEED: "Fil",
  SPORTSBOOK: "Sport",
  DISCOVERY: "Découverte",
  CASINO: "Casino",
  SOCIAL_CASINO: "Casino",
  PEER_TO_PEER_NAV: "Pair-à-pair",
  PEER_TO_PEER: "Pair-à-pair",
  HOME: "accueil",
  PROFILE: "Profil",
  TILE_LIVE_SPORTS: "En direct",
  TILE_PEER_TO_PEER: "Pair à pair",
  MOBILE_TILE_ALL_SPORTS: "Tous sports",
  MOBILE_TILE_LIVE_SPO: "Direct.",
  BET_BUILDER: "Créat. Pari",
  BETBUILDER: "Créat. Pari",
  PEER_TO_PEER_BTN: "Pair-à-pair",
  PEER_TO_PEER_SHORT: "Pair-à-pair",
  SIGN_IN: "Se connecter",
  CREATE_ACCOUNT: "Créer un compte",
  SEE_MORE: "VOIR PLUS",
  MORE_BETS: "PLUS DE PARIS",
  VIEW_TIPS: "Voir les conseils",
  BACK_TO_SPORTS: "Retour aux sports",
  SHARE: "Partager",
  COLLAPSE: "Réduire",
  SHOW_ALL_LEGS: "Voir tous les paris",
  PLACE_A_BET: "Parier",
  MAKE_BETS: "Placer des paris",
  WELCOME_BONUS: "BONUS DE BIENVENUE",
  WELCOME_BONUS_PROMO: "OBTENEZ UN BONUS DE 100% SUR VOTRE PREMIER DÉPÔT",
  WELCOME_BONUS_BODY_WEB: "Profitez d'un bonus de bienvenue de 100% sur votre premier dépôt.",
  WELCOME_BONUS_BODY_MOBILE: "Obtenez un pari gratuit ou 50% de crédit casino supplémentaire",
  WELCOME_BONUS_SUBTITLE: "Profitez d'un bonus de bienvenue de 100% sur votre premier dépôt.",
  LIVE_AND_UPCOMING: "En direct & À venir",
  LIVE_AND_UPCOMING_GAMES: "Matchs en direct & À venir",
  ALL_SPORTS: "Tous les sports",
  POPULAR: "Populaire",
  POPULAR_LEAGUES: "Ligues populaires",
  DISCOVER: "Découvrir",
  CASINO_HEADING: "Casino",
  SEARCH: "Rechercher",
  SEARCH_PLACEHOLDER: "Rechercher équipes, joueurs et événements",
  SEARCH_TEAMS_PLAYERS_EVENTS: "Rechercher équipes, joueurs et événements",
  TAB_MY_BETS: "Mes paris",
  MY_BETS: "Mes paris",
  TAB_MY_FEED: "Mon fil",
  MY_FEED: "Mon fil",
  TAB_FRIENDS: "Amis",
  TAB_EXPLORE: "Explorer",
  TAB_SPORTS: "Sports",
  TAB_ALL_SPORTS: "Tous les sports",
  FILTER_ALL: "Tous",
  FILTER_PENDING: "En attente",
  FILTER_SETTLED: "Réglé",
  STATUS_WON: "GAGNÉ",
  STATUS_LOST: "PERDU",
  STATUS_PENDING: "EN ATTENTE",
  STATUS_LIVE: "EN DIRECT",
  WON: "GAGNÉ",
  LOST: "PERDU",
  PENDING: "EN ATTENTE",
  VOID: "ANNULÉ",
  LIVE_TAG: "• Direct",
  SETTLED: "Réglé",
  STAKE: "MISE",
  PAYOUT: "GAIN",
  POTENTIAL: "POTENTIEL",
  OUTCOME: "RÉSULTAT",
  ODDS_LABEL: "COTES",
  FLEX_CUTS: "FLEX CUTS",
  LEG_PARLAY: "Sélection Multi",
  MONEYLINE: "Vainqueur",
  OVER_UNDER: "Plus/Moins",
  SPREAD: "Handicap",
  BETSLIP_PARLAY_ODDS: "Cotes Multi",
  BETSLIP: "Coupon de pari",
  EMPTY_BET_SLIP_HEADING: "Coupon vide",
  EMPTY_BET_SLIP_DESCRIPTION: "Cliquez sur les cotes pour ajouter au coupon",
  SOCCER: "Football",
  BASKETBALL: "Basketball",
  TENNIS: "Tennis",
  TABLE_TENNIS: "Tennis de table",
  VOLLEYBALL: "Volleyball",
  ICE_HOCKEY: "Hockey sur glace",
  AMERICAN_FOOTBALL: "Football américain",
  RUGBY: "Rugby",
  VIRTUAL: "Virtuels",
  FOLLOWING: "Abonnements",
  FOLLOWERS: "Abonnés",
  REFER_FRIENDS: "Parrainer des amis",
  GET_BONUS_1: "Parrainez vos amis et développez votre réseau de paris",
  GET_BONUS_2: "Ami à la fois",
  WINS: "Victoires",
  TOTAL_BALANCE: "Solde total",
  AVAILABLE_TO_REDEEM: "Solde retirable",
  PURCHASE: "Dépôt",
  PRIZE_REDEMPTION: "Retrait",
  TRANSACTION_HISTORY: "Historique des transactions",
  AVAILABLE_BONUSES: "Bonus disponibles",
  TOP_5_CASINO_GAMES: "Top 5 jeux de casino",
  PEER_TO_PEER_HEADING: "Mes paris pair-à-pair",
  PENDING_INVITES: "Invitations en attente",
  CURRENT_BETS: "Paris en cours",
  PAST_BETS: "Paris passés",
  HISTORY: "Historique",
  NO_P2P_BETS: "Aucun pari P2P",
  COMING_SOON: "Bientôt disponible",
  LIVE_BADGE: "EN DIRECT",
};

const PT_STRINGS: Partial<TCMStrings> = {
  CASH: "Kwanza",
  FEED: "Feed",
  SPORTSBOOK: "Desportos",
  DISCOVERY: "Descoberta",
  CASINO: "Cassino",
  SOCIAL_CASINO: "Cassino",
  PEER_TO_PEER_NAV: "Par-a-par",
  PEER_TO_PEER: "Par-a-par",
  HOME: "início",
  PROFILE: "Perfil",
  TILE_LIVE_SPORTS: "Ao vivo",
  TILE_PEER_TO_PEER: "Par a Par",
  MOBILE_TILE_ALL_SPORTS: "Tod. Desp.",
  BET_BUILDER: "Criar Aposta",
  BETBUILDER: "Criar Aposta",
  PEER_TO_PEER_BTN: "Par-a-par",
  PEER_TO_PEER_SHORT: "Par-a-par",
  SIGN_IN: "Entrar",
  CREATE_ACCOUNT: "Criar conta",
  SEE_MORE: "VER MAIS",
  MORE_BETS: "MAIS APOSTAS",
  VIEW_TIPS: "Ver dicas",
  BACK_TO_SPORTS: "Voltar a Desportos",
  SHARE: "Partilhar",
  COLLAPSE: "Fechar",
  SHOW_ALL_LEGS: "Ver todas as apostas",
  PLACE_A_BET: "Apostar",
  MAKE_BETS: "Fazer apostas",
  WELCOME_BONUS: "BÓNUS DE BOAS-VINDAS",
  WELCOME_BONUS_PROMO: "OBTENHA 100% DE BÓNUS NO SEU PRIMEIRO DEPÓSITO",
  WELCOME_BONUS_BODY_WEB: "Desfrute de 100% de bónus de boas-vindas no seu primeiro depósito.",
  WELCOME_BONUS_BODY_MOBILE: "Obtenha uma aposta gratuita ou 50% mais créditos de cassino",
  WELCOME_BONUS_SUBTITLE: "Desfrute de 100% de bónus de boas-vindas no seu primeiro depósito.",
  LIVE_AND_UPCOMING: "Ao vivo e próximos",
  LIVE_AND_UPCOMING_GAMES: "Jogos ao vivo e próximos",
  ALL_SPORTS: "Todos os desportos",
  POPULAR: "Popular",
  POPULAR_LEAGUES: "Ligas populares",
  DISCOVER: "Descobrir",
  CASINO_HEADING: "Cassino",
  SEARCH: "Pesquisar",
  SEARCH_PLACEHOLDER: "Pesquisar equipas, jogadores e eventos",
  SEARCH_TEAMS_PLAYERS_EVENTS: "Pesquisar equipas, jogadores e eventos",
  TAB_MY_BETS: "Minhas apostas",
  MY_BETS: "Minhas apostas",
  TAB_MY_FEED: "Meu feed",
  MY_FEED: "Meu feed",
  TAB_FRIENDS: "Amigos",
  TAB_EXPLORE: "Explorar",
  TAB_SPORTS: "Desportos",
  TAB_ALL_SPORTS: "Todos os desportos",
  FILTER_ALL: "Todos",
  FILTER_PENDING: "Pendente",
  FILTER_SETTLED: "Liquidado",
  STATUS_WON: "GANHOU",
  STATUS_LOST: "PERDEU",
  STATUS_PENDING: "PENDENTE",
  STATUS_LIVE: "AO VIVO",
  WON: "GANHOU",
  LOST: "PERDEU",
  PENDING: "PENDENTE",
  VOID: "ANULADO",
  LIVE_TAG: "• Ao vivo",
  SETTLED: "Liquidado",
  STAKE: "APOSTA",
  PAYOUT: "PAGAMENTO",
  POTENTIAL: "POTENCIAL",
  OUTCOME: "RESULTADO",
  ODDS_LABEL: "ODDS",
  FLEX_CUTS: "FLEX CUTS",
  LEG_PARLAY: "Seleção Multi",
  MONEYLINE: "Vencedor",
  OVER_UNDER: "Mais/Menos",
  SPREAD: "Handicap",
  BETSLIP_PARLAY_ODDS: "Odds Multi",
  BETSLIP: "Boletim de apostas",
  EMPTY_BET_SLIP_HEADING: "Boletim vazio",
  EMPTY_BET_SLIP_DESCRIPTION: "Clique nas odds para adicionar ao boletim",
  SOCCER: "Futebol",
  BASKETBALL: "Basquetebol",
  TENNIS: "Ténis",
  TABLE_TENNIS: "Ténis de mesa",
  VOLLEYBALL: "Voleibol",
  ICE_HOCKEY: "Hóquei no gelo",
  AMERICAN_FOOTBALL: "Futebol americano",
  RUGBY: "Rugby",
  VIRTUAL: "Virtuais",
  FOLLOWING: "A seguir",
  FOLLOWERS: "Seguidores",
  REFER_FRIENDS: "Indicar amigos",
  GET_BONUS_1: "Indique os seus amigos e construa a sua rede de apostas",
  GET_BONUS_2: "Amigo de cada vez",
  WINS: "Vitórias",
  TOTAL_BALANCE: "Saldo total",
  AVAILABLE_TO_REDEEM: "Saldo disponível",
  PURCHASE: "Depósito",
  PRIZE_REDEMPTION: "Levantamento",
  TRANSACTION_HISTORY: "Histórico de transações",
  AVAILABLE_BONUSES: "Bónus disponíveis",
  TOP_5_CASINO_GAMES: "Top 5 jogos de cassino",
  PEER_TO_PEER_HEADING: "Minhas apostas par-a-par",
  PENDING_INVITES: "Convites pendentes",
  CURRENT_BETS: "Apostas atuais",
  PAST_BETS: "Apostas passadas",
  HISTORY: "Histórico",
  NO_P2P_BETS: "Sem apostas P2P",
  COMING_SOON: "Em breve",
  LIVE_BADGE: "AO VIVO",
};

const SW_STRINGS: Partial<TCMStrings> = {
  CASH: "Shilingi",
  FEED: "Mpasho",
  SPORTSBOOK: "Michezo",
  DISCOVERY: "Ugunduzi",
  CASINO: "Kasino",
  SOCIAL_CASINO: "Kasino",
  PEER_TO_PEER_NAV: "Mtu kwa Mtu",
  PEER_TO_PEER: "Mtu kwa Mtu",
  HOME: "nyumbani",
  PROFILE: "Wasifu",
  TILE_LIVE_SPORTS: "Moja kwa Moja",
  TILE_PEER_TO_PEER: "Mtu kwa Mtu",
  MOBILE_TILE_ALL_SPORTS: "Mchezo wote",
  MOBILE_TILE_LIVE_SPO: "Moja kwa Moja",
  BET_BUILDER: "Jenga Dau",
  BETBUILDER: "Jenga Dau",
  PEER_TO_PEER_BTN: "Mtu kwa Mtu",
  PEER_TO_PEER_SHORT: "Mtu kwa Mtu",
  SIGN_IN: "Ingia",
  CREATE_ACCOUNT: "Fungua akaunti",
  SEE_MORE: "TAZAMA ZAIDI",
  MORE_BETS: "DAU ZAIDI",
  VIEW_TIPS: "Tazama vidokezo",
  BACK_TO_SPORTS: "Rudi kwa Michezo",
  SHARE: "Shiriki",
  COLLAPSE: "Funga",
  SHOW_ALL_LEGS: "Onyesha dau zote",
  PLACE_A_BET: "Weka Dau",
  MAKE_BETS: "Weka Madau",
  WELCOME_BONUS: "BONASI YA KARIBU",
  WELCOME_BONUS_PROMO: "PATA BONASI YA 100% KWENYE AMANA YAKO YA KWANZA",
  WELCOME_BONUS_BODY_WEB: "Furahia bonasi ya 100% ya karibu kwenye amana yako ya kwanza.",
  WELCOME_BONUS_BODY_MOBILE: "Pata mchezo wa dau bila malipo au 50% zaidi ya fedha za kasino",
  WELCOME_BONUS_SUBTITLE: "Furahia bonasi ya 100% ya karibu kwenye amana yako ya kwanza.",
  LIVE_AND_UPCOMING: "Moja kwa Moja na Zijazo",
  LIVE_AND_UPCOMING_GAMES: "Michezo ya Moja kwa Moja na Zijazo",
  ALL_SPORTS: "Michezo Yote",
  POPULAR: "Maarufu",
  POPULAR_LEAGUES: "Ligi Maarufu",
  DISCOVER: "Gundua",
  CASINO_HEADING: "Kasino",
  SEARCH: "Tafuta",
  SEARCH_PLACEHOLDER: "Tafuta timu, wachezaji na matukio",
  SEARCH_TEAMS_PLAYERS_EVENTS: "Tafuta timu, wachezaji na matukio",
  TAB_MY_BETS: "Dau Zangu",
  MY_BETS: "Dau Zangu",
  TAB_MY_FEED: "Mpasho Wangu",
  MY_FEED: "Mpasho Wangu",
  TAB_FRIENDS: "Marafiki",
  TAB_EXPLORE: "Chunguza",
  TAB_SPORTS: "Michezo",
  TAB_ALL_SPORTS: "Michezo Yote",
  FILTER_ALL: "Yote",
  FILTER_PENDING: "Inasubiri",
  FILTER_SETTLED: "Kulipwa",
  STATUS_WON: "UMESHINDA",
  STATUS_LOST: "UMEPOTEZA",
  STATUS_PENDING: "INASUBIRI",
  STATUS_LIVE: "MOJA KWA MOJA",
  WON: "UMESHINDA",
  LOST: "UMEPOTEZA",
  PENDING: "INASUBIRI",
  VOID: "BATILISHWA",
  LIVE_TAG: "• Moja kwa Moja",
  SETTLED: "Kulipwa",
  STAKE: "KIASI",
  PAYOUT: "MALIPO",
  POTENTIAL: "UWEZEKANO",
  OUTCOME: "MATOKEO",
  ODDS_LABEL: "UWEZEKANO",
  FLEX_CUTS: "FLEX CUTS",
  LEG_PARLAY: "Chaguo Nyingi",
  MONEYLINE: "Mshindi wa Mechi",
  OVER_UNDER: "Zaidi/Chini",
  SPREAD: "Handicap",
  BETSLIP_PARLAY_ODDS: "Uwezekano wa Multi",
  BETSLIP: "Kadi ya Dau",
  EMPTY_BET_SLIP_HEADING: "Kadi ya Dau iko wazi",
  EMPTY_BET_SLIP_DESCRIPTION: "Bonyeza uwezekano kuongeza kwenye kadi",
  SOCCER: "Mpira wa Miguu",
  BASKETBALL: "Besiketi",
  TENNIS: "Tenisi",
  TABLE_TENNIS: "Tenisi ya Meza",
  VOLLEYBALL: "Mpira wa Wavu",
  ICE_HOCKEY: "Hoki ya Barafu",
  AMERICAN_FOOTBALL: "Mpira wa Marekani",
  RUGBY: "Ragbi",
  VIRTUAL: "Maonyesho",
  FOLLOWING: "Unaofuatilia",
  FOLLOWERS: "Wanaokufuata",
  REFER_FRIENDS: "Alika marafiki",
  GET_BONUS_1: "Alika marafiki wako na uunde mtandao wako wa kubashiri",
  GET_BONUS_2: "Rafiki kwa wakati mmoja",
  WINS: "Ushindi",
  TOTAL_BALANCE: "Jumla ya salio",
  AVAILABLE_TO_REDEEM: "Salio linaloweza kutolewa",
  PURCHASE: "Weka Pesa",
  PRIZE_REDEMPTION: "Toa Pesa",
  TRANSACTION_HISTORY: "Historia ya miamala",
  AVAILABLE_BONUSES: "Bonasi zinazopatikana",
  TOP_5_CASINO_GAMES: "Michezo 5 Bora ya Kasino",
  PEER_TO_PEER_HEADING: "Madau yangu mtu kwa mtu",
  PENDING_INVITES: "Mialiko inayosubiri",
  CURRENT_BETS: "Madau ya sasa",
  PAST_BETS: "Madau ya zamani",
  HISTORY: "Historia",
  NO_P2P_BETS: "Hakuna dau za P2P",
  COMING_SOON: "Inakuja hivi karibuni",
  LIVE_BADGE: "MOJA KWA MOJA",
};

const YO_STRINGS: Partial<TCMStrings> = {
  CASH: "Naira",
  FEED: "Agbeko",
  SPORTSBOOK: "Ere-idaraya",
  DISCOVERY: "Iwari",
  CASINO: "Kasino",
  SOCIAL_CASINO: "Kasino",
  PEER_TO_PEER_NAV: "Eniyan-si-Eniyan",
  PEER_TO_PEER: "Eniyan-si-Eniyan",
  HOME: "ile",
  PROFILE: "Profaili",
  BET_BUILDER: "Kọ Tẹtẹ",
  BETBUILDER: "Kọ Tẹtẹ",
  PEER_TO_PEER_BTN: "Eniyan-si-Eniyan",
  PEER_TO_PEER_SHORT: "Eniyan-si-Eniyan",
  SIGN_IN: "Wọle",
  CREATE_ACCOUNT: "Ṣẹda àkọọlẹ",
  SEE_MORE: "WO SIWAJU",
  MORE_BETS: "TẸTẸ SIWAJU",
  VIEW_TIPS: "Wo Àwọn Imọ",
  BACK_TO_SPORTS: "Padà sí Ere",
  SHARE: "Pin",
  COLLAPSE: "Tì",
  SHOW_ALL_LEGS: "Ṣafihan gbogbo àwọn tẹtẹ",
  PLACE_A_BET: "Fi Tẹtẹ",
  MAKE_BETS: "Ṣe Àwọn Tẹtẹ",
  WELCOME_BONUS: "ẸBỌ KAABỌ",
  WELCOME_BONUS_PROMO: "GBA ẸBỌ 100% LORI IDOGO RẸ ÀKỌKỌ",
  WELCOME_BONUS_BODY_WEB: "Gbadun ẹbọ kaabọ 100% lori idogo rẹ àkọkọ.",
  WELCOME_BONUS_BODY_MOBILE: "Gba ere tẹtẹ ọfẹ tabi 50% siwaju sii ti owo kasino",
  WELCOME_BONUS_SUBTITLE: "Gbadun ẹbọ kaabọ 100% lori idogo rẹ àkọkọ.",
  LIVE_AND_UPCOMING: "Laaye ati Awọn Tó Ń Bọ̀",
  LIVE_AND_UPCOMING_GAMES: "Awọn Ere Laaye ati Awọn Tó Ń Bọ̀",
  ALL_SPORTS: "Gbogbo Ere",
  POPULAR: "Gbajúmọ̀",
  POPULAR_LEAGUES: "Àwọn Ìjọ Gbajúmọ̀",
  DISCOVER: "Ṣàwárí",
  CASINO_HEADING: "Kasino",
  SEARCH: "Wá",
  SEARCH_PLACEHOLDER: "Wá àwọn ẹgbẹ, àwọn ẹrọ-ìdárayá àti àwọn ìṣẹ̀lẹ̀",
  SEARCH_TEAMS_PLAYERS_EVENTS: "Wá àwọn ẹgbẹ, àwọn ẹrọ-ìdárayá àti àwọn ìṣẹ̀lẹ̀",
  TAB_MY_BETS: "Tẹtẹ Mi",
  MY_BETS: "Tẹtẹ Mi",
  TAB_MY_FEED: "Agbeko Mi",
  MY_FEED: "Agbeko Mi",
  TAB_FRIENDS: "Àwọn Ọrẹ",
  TAB_EXPLORE: "Ṣàwárí",
  TAB_SPORTS: "Ere-idaraya",
  TAB_ALL_SPORTS: "Gbogbo Ere",
  FILTER_ALL: "Gbogbo",
  FILTER_PENDING: "Tí ń Dúró",
  FILTER_SETTLED: "Ti Pari",
  STATUS_WON: "BORI",
  STATUS_LOST: "PADANU",
  STATUS_PENDING: "NÍ ÌDÁWỌLÉ",
  STATUS_LIVE: "LAAYE",
  WON: "BORI",
  LOST: "PADANU",
  PENDING: "NÍ ÌDÁWỌLÉ",
  VOID: "FAGILEE",
  LIVE_TAG: "• Laaye",
  SETTLED: "Ti Pari",
  STAKE: "ÌDOKOWÒ",
  PAYOUT: "SISANWÓ",
  POTENTIAL: "ṢEÉṢE",
  OUTCOME: "ÈSÌ",
  ODDS_LABEL: "ÀṢÀ",
  FLEX_CUTS: "FLEX CUTS",
  LEG_PARLAY: "Ìpínpín Tẹtẹ",
  MONEYLINE: "Olubori Ìdíje",
  OVER_UNDER: "Àárọ̀/Àbẹ",
  SPREAD: "Ipin",
  BETSLIP_PARLAY_ODDS: "Àwọn ÀṢÀ Tẹtẹ",
  BETSLIP: "Iwe Tẹtẹ",
  EMPTY_BET_SLIP_HEADING: "Iwe Tẹtẹ ṣòfo",
  EMPTY_BET_SLIP_DESCRIPTION: "Tẹ lori àwọn àṣà lati fi kun iwe tẹtẹ",
  SOCCER: "Bọọlù ẹsẹ",
  BASKETBALL: "Bọọlù agbọn",
  TENNIS: "Tẹnisi",
  TABLE_TENNIS: "Tẹnisi Tábìlì",
  VOLLEYBALL: "Bọọlù àpò",
  ICE_HOCKEY: "Hoki yinyin",
  AMERICAN_FOOTBALL: "Bọọlù ẹsẹ Amẹrika",
  RUGBY: "Ragbi",
  VIRTUAL: "Àgbáyé Àfọwọyà",
  FOLLOWING: "Tí ń Tọ̀",
  FOLLOWERS: "Àwọn Tẹ̀lé",
  REFER_FRIENDS: "Mú àwọn ọrẹ wá",
  GET_BONUS_1: "Mú àwọn ọrẹ rẹ wá kọ́ nẹtiwọọki tẹtẹ rẹ",
  GET_BONUS_2: "Ọrẹ ni ẹẹkan",
  WINS: "Ìborí",
  TOTAL_BALANCE: "Iye owo lapapọ",
  AVAILABLE_TO_REDEEM: "Iye owo tí o lè yọ",
  PURCHASE: "Fi owo sii",
  PRIZE_REDEMPTION: "Yọ owo",
  TRANSACTION_HISTORY: "Ìtàn àwọn ìṣòwò",
  AVAILABLE_BONUSES: "Àwọn ẹbọ tí o wà",
  TOP_5_CASINO_GAMES: "Àwọn ere kasino 5 tí o gbajúmọ̀",
  PEER_TO_PEER_HEADING: "Àwọn tẹtẹ mi eniyan-si-eniyan",
  PENDING_INVITES: "Àwọn ìpè tí ń dúró",
  CURRENT_BETS: "Àwọn tẹtẹ lọwọlọwọ",
  PAST_BETS: "Àwọn tẹtẹ tẹlẹ",
  HISTORY: "Ìtàn",
  NO_P2P_BETS: "Ko si tẹtẹ P2P",
  COMING_SOON: "Ń bọ laipẹ",
  LIVE_BADGE: "LAAYE",
};

const HA_STRINGS: Partial<TCMStrings> = {
  CASH: "Naira",
  FEED: "Labarai",
  SPORTSBOOK: "Wasanni",
  DISCOVERY: "Gano",
  CASINO: "Kasino",
  SOCIAL_CASINO: "Kasino",
  PEER_TO_PEER_NAV: "Mutum-da-Mutum",
  PEER_TO_PEER: "Mutum-da-Mutum",
  HOME: "gida",
  PROFILE: "Bayani",
  BET_BUILDER: "Gina Caca",
  BETBUILDER: "Gina Caca",
  PEER_TO_PEER_BTN: "Mutum-da-Mutum",
  PEER_TO_PEER_SHORT: "Mutum-da-Mutum",
  SIGN_IN: "Shiga",
  CREATE_ACCOUNT: "Ƙirƙiri asusun",
  SEE_MORE: "DUBA ƘARI",
  MORE_BETS: "ƘARIN CACAƘAN",
  VIEW_TIPS: "Duba Shawarwari",
  BACK_TO_SPORTS: "Koma ga Wasanni",
  SHARE: "Raba",
  COLLAPSE: "Rufe",
  SHOW_ALL_LEGS: "Nuna duk cacaƙan",
  PLACE_A_BET: "Yi Caca",
  MAKE_BETS: "Yi Cacaƙan",
  WELCOME_BONUS: "KYAUTA NA MARABA",
  WELCOME_BONUS_PROMO: "SAMU KYAUTA 100% A ADANKU NA FARKO",
  WELCOME_BONUS_BODY_WEB: "Ji daɗin kyauta ta maraba ta 100% a adanku na farko.",
  WELCOME_BONUS_BODY_MOBILE: "Samu kyautan wasannin ko 50% ƙari na kuɗin kasino",
  WELCOME_BONUS_SUBTITLE: "Ji daɗin kyauta ta maraba ta 100% a adanku na farko.",
  LIVE_AND_UPCOMING: "Kai tsaye da Masu Zuwa",
  LIVE_AND_UPCOMING_GAMES: "Wasannin Kai tsaye da Masu Zuwa",
  ALL_SPORTS: "Duk Wasanni",
  POPULAR: "Shahararru",
  POPULAR_LEAGUES: "Ƙungiyoyin Shahararru",
  DISCOVER: "Gano",
  CASINO_HEADING: "Kasino",
  SEARCH: "Bincika",
  SEARCH_PLACEHOLDER: "Binciki ƙungiyoyi, 'yan wasa da abubuwan da suka faru",
  SEARCH_TEAMS_PLAYERS_EVENTS: "Binciki ƙungiyoyi, 'yan wasa da abubuwan da suka faru",
  TAB_MY_BETS: "Cacaƙana",
  MY_BETS: "Cacaƙana",
  TAB_MY_FEED: "Labarina",
  MY_FEED: "Labarina",
  TAB_FRIENDS: "Abokai",
  TAB_EXPLORE: "Binciko",
  TAB_SPORTS: "Wasanni",
  TAB_ALL_SPORTS: "Duk Wasanni",
  FILTER_ALL: "Duka",
  FILTER_PENDING: "Ana Jira",
  FILTER_SETTLED: "An Biya",
  STATUS_WON: "YA CI",
  STATUS_LOST: "YA KASA",
  STATUS_PENDING: "ANA JIRA",
  STATUS_LIVE: "KAI TSAYE",
  WON: "YA CI",
  LOST: "YA KASA",
  PENDING: "ANA JIRA",
  VOID: "SOKE",
  LIVE_TAG: "• Kai tsaye",
  SETTLED: "An Biya",
  STAKE: "KUƊADE",
  PAYOUT: "BIYAN KUƊI",
  POTENTIAL: "IYAWA",
  OUTCOME: "SAKAMAKON",
  ODDS_LABEL: "DAMAR",
  FLEX_CUTS: "FLEX CUTS",
  LEG_PARLAY: "Zaɓi Yawa",
  MONEYLINE: "Mai Nasara",
  OVER_UNDER: "Sama/Ƙasa",
  SPREAD: "Kayyade",
  BETSLIP_PARLAY_ODDS: "Damar Yawa",
  BETSLIP: "Takardar Caca",
  EMPTY_BET_SLIP_HEADING: "Takardar Caca tana wofi",
  EMPTY_BET_SLIP_DESCRIPTION: "Danna damar don ƙara zuwa takardar caca",
  SOCCER: "Ƙwallon ƙafa",
  BASKETBALL: "Ƙwallon Kwando",
  TENNIS: "Tenis",
  TABLE_TENNIS: "Ƙwallon Tebur",
  VOLLEYBALL: "Ƙwallon Raga",
  ICE_HOCKEY: "Hockey a Kankara",
  AMERICAN_FOOTBALL: "Ƙwallon Amurka",
  RUGBY: "Rugby",
  VIRTUAL: "Wasannin Dijital",
  FOLLOWING: "Ana bin",
  FOLLOWERS: "Mabiya",
  REFER_FRIENDS: "Gayyatar abokai",
  GET_BONUS_1: "Gayyata abokanka ka gina hanyar caca ta zamantakewa",
  GET_BONUS_2: "Aboki daya bayan daya",
  WINS: "Nasarori",
  TOTAL_BALANCE: "Duk adadin kuɗi",
  AVAILABLE_TO_REDEEM: "Kuɗin da za a iya cirewa",
  PURCHASE: "Adana Kuɗi",
  PRIZE_REDEMPTION: "Cire Kuɗi",
  TRANSACTION_HISTORY: "Tarihin ma'amaloli",
  AVAILABLE_BONUSES: "Kyaututukan da ake da su",
  TOP_5_CASINO_GAMES: "Manyan wasannin kasino 5",
  PEER_TO_PEER_HEADING: "Cacaƙana na mutum-da-mutum",
  PENDING_INVITES: "Gayyace da ke jiran",
  CURRENT_BETS: "Cacaƙan yanzu",
  PAST_BETS: "Cacaƙan da suka wuce",
  HISTORY: "Tarihi",
  NO_P2P_BETS: "Babu cacaƙin P2P",
  COMING_SOON: "Zuwa ba da daɗewa ba",
  LIVE_BADGE: "KAI TSAYE",
};

const AR_STRINGS: Partial<TCMStrings> = {
  CASH: "درهم",
  FEED: "الخلاصة",
  SPORTSBOOK: "الرياضة",
  DISCOVERY: "الاكتشاف",
  CASINO: "كازينو",
  SOCIAL_CASINO: "كازينو",
  PEER_TO_PEER_NAV: "نظير لنظير",
  PEER_TO_PEER: "نظير لنظير",
  HOME: "الرئيسية",
  PROFILE: "الملف الشخصي",
  BET_BUILDER: "منشئ الرهانات",
  BETBUILDER: "منشئ الرهانات",
  PEER_TO_PEER_BTN: "نظير لنظير",
  PEER_TO_PEER_SHORT: "نظير لنظير",
  SIGN_IN: "تسجيل الدخول",
  CREATE_ACCOUNT: "إنشاء حساب",
  SEE_MORE: "عرض المزيد",
  MORE_BETS: "مزيد من الرهانات",
  VIEW_TIPS: "عرض النصائح",
  BACK_TO_SPORTS: "العودة إلى الرياضات",
  SHARE: "مشاركة",
  COLLAPSE: "طي",
  SHOW_ALL_LEGS: "عرض جميع الأرجل",
  PLACE_A_BET: "ضع رهاناً",
  MAKE_BETS: "وضع رهانات",
  WELCOME_BONUS: "مكافأة الترحيب",
  WELCOME_BONUS_PROMO: "احصل على مكافأة 100% على إيداعك الأول",
  WELCOME_BONUS_BODY_WEB: "استمتع بمكافأة ترحيب 100% على إيداعك الأول وضاعف رهانك.",
  WELCOME_BONUS_BODY_MOBILE: "احصل على رهان رياضي مجاني أو 50% إضافية من رصيد الكازينو",
  WELCOME_BONUS_SUBTITLE: "استمتع بمكافأة ترحيب 100% على إيداعك الأول وضاعف رهانك.",
  LIVE_AND_UPCOMING: "مباشر والقادمة",
  LIVE_AND_UPCOMING_GAMES: "المباريات المباشرة والقادمة",
  ALL_SPORTS: "جميع الرياضات",
  POPULAR: "شائع",
  POPULAR_LEAGUES: "الدوريات الشائعة",
  DISCOVER: "اكتشف",
  CASINO_HEADING: "كازينو",
  SEARCH: "بحث",
  SEARCH_PLACEHOLDER: "البحث عن فرق، لاعبين وأحداث",
  SEARCH_TEAMS_PLAYERS_EVENTS: "البحث عن فرق، لاعبين وأحداث",
  TAB_MY_BETS: "رهاناتي",
  MY_BETS: "رهاناتي",
  TAB_MY_FEED: "موجزي",
  MY_FEED: "موجزي",
  TAB_FRIENDS: "الأصدقاء",
  TAB_EXPLORE: "استكشاف",
  TAB_SPORTS: "الرياضة",
  TAB_ALL_SPORTS: "جميع الرياضات",
  FILTER_ALL: "الكل",
  FILTER_PENDING: "قيد الانتظار",
  FILTER_SETTLED: "مستوفى",
  STATUS_WON: "فاز",
  STATUS_LOST: "خسر",
  STATUS_PENDING: "قيد الانتظار",
  STATUS_LIVE: "مباشر",
  WON: "فاز",
  LOST: "خسر",
  PENDING: "قيد الانتظار",
  VOID: "ملغي",
  LIVE_TAG: "• مباشر",
  SETTLED: "مستوفى",
  STAKE: "الرهان",
  PAYOUT: "المكاسب",
  POTENTIAL: "المحتمل",
  OUTCOME: "النتيجة",
  ODDS_LABEL: "الحظوظ",
  FLEX_CUTS: "FLEX CUTS",
  LEG_PARLAY: "تحديدات متعددة",
  MONEYLINE: "الفائز",
  OVER_UNDER: "أكثر/أقل",
  SPREAD: "هانديكاب",
  BETSLIP_PARLAY_ODDS: "حظوظ متعددة",
  BETSLIP: "قسيمة الرهان",
  EMPTY_BET_SLIP_HEADING: "القسيمة فارغة",
  EMPTY_BET_SLIP_DESCRIPTION: "انقر على الحظوظ للإضافة إلى القسيمة",
  SOCCER: "كرة القدم",
  BASKETBALL: "كرة السلة",
  TENNIS: "كرة المضرب",
  TABLE_TENNIS: "تنس الطاولة",
  VOLLEYBALL: "الكرة الطائرة",
  ICE_HOCKEY: "هوكي الجليد",
  AMERICAN_FOOTBALL: "كرة القدم الأمريكية",
  RUGBY: "الرغبي",
  VIRTUAL: "الرياضة الافتراضية",
  FOLLOWING: "المتابَعون",
  FOLLOWERS: "المتابعون",
  REFER_FRIENDS: "دعوة أصدقاء",
  GET_BONUS_1: "ادعُ أصدقاءك وابنِ شبكة رهاناتك الاجتماعية",
  GET_BONUS_2: "صديق في كل مرة",
  WINS: "انتصارات",
  TOTAL_BALANCE: "الرصيد الإجمالي",
  AVAILABLE_TO_REDEEM: "الرصيد القابل للسحب",
  PURCHASE: "إيداع",
  PRIZE_REDEMPTION: "سحب",
  TRANSACTION_HISTORY: "سجل المعاملات",
  AVAILABLE_BONUSES: "المكافآت المتاحة",
  TOP_5_CASINO_GAMES: "أفضل 5 ألعاب كازينو",
  PEER_TO_PEER_HEADING: "رهاناتي نظير لنظير",
  PENDING_INVITES: "الدعوات المعلقة",
  CURRENT_BETS: "الرهانات الحالية",
  PAST_BETS: "الرهانات السابقة",
  HISTORY: "السجل",
  NO_P2P_BETS: "لا رهانات P2P",
  COMING_SOON: "قريباً",
  LIVE_BADGE: "مباشر",
};

export const LANGUAGE_NAMES: Record<Language, string> = {
  en: "English",
  fr: "Français",
  pt: "Português",
  sw: "Kiswahili",
  yo: "Yorùbá",
  ha: "Hausa",
  ar: "العربية",
};

export const LANGUAGE_TRANSLATIONS: Record<Language, Partial<TCMStrings>> = {
  en: {},
  fr: FR_STRINGS,
  pt: PT_STRINGS,
  sw: SW_STRINGS,
  yo: YO_STRINGS,
  ha: HA_STRINGS,
  ar: AR_STRINGS,
};

export function getStrings(language: Language = "en", overrides?: Partial<TCMStrings>): TCMStrings {
  const base: TCMStrings =
    language === "en"
      ? DEFAULT_STRINGS
      : { ...DEFAULT_STRINGS, ...LANGUAGE_TRANSLATIONS[language] };
  return overrides ? { ...base, ...overrides } : base;
}
