import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, Sparkles } from "lucide-react";

interface ActiveLandingPageCardProps {
  clientId: string;
}

export function ActiveLandingPageCard({ clientId }: ActiveLandingPageCardProps) {
  return (
    <Link to="/onboarding/$clientId/studio" params={{ clientId }} className="block">
      <div className="group relative overflow-hidden rounded-2xl border border-primary/30 bg-gradient-to-br from-primary/10 via-primary/5 to-transparent p-6 transition-all hover:border-primary/50 hover:shadow-premium cursor-pointer">
        {/* Decorative glow */}
        <div className="pointer-events-none absolute top-0 right-0 h-40 w-40 -translate-y-12 translate-x-12 rounded-full bg-gradient-to-bl from-primary/20 to-transparent blur-3xl" />

        {/* Available Now badge */}
        <div className="absolute top-4 right-4 z-10 flex items-center gap-1.5 rounded-full border border-primary/40 bg-primary/10 px-2.5 py-1 backdrop-blur-sm">
          <div className="h-1.5 w-1.5 animate-pulse rounded-full bg-primary" />
          <span className="text-[10px] font-semibold uppercase tracking-wider text-primary">
            Available Now
          </span>
        </div>

        <div className="relative space-y-4">
          {/* Icon */}
          <div className="flex h-12 w-12 items-center justify-center rounded-xl border border-primary/20 bg-primary/10">
            <Sparkles className="h-5 w-5 text-primary" />
          </div>

          {/* Title */}
          <div>
            <div className="flex flex-wrap items-center gap-2">
              <h3 className="text-base font-semibold text-foreground">Landing Page Generator</h3>
              <span className="text-[10px] uppercase tracking-[0.15em] text-muted-foreground">
                Powered by Anthropic
              </span>
            </div>
            <p className="mt-2 max-w-xl text-xs leading-relaxed text-muted-foreground">
              Create your branded landing page, terms of service, privacy policy, and responsible
              gambling pages — all generated by AI in under 5 minutes.
            </p>
          </div>

          {/* Feature list */}
          <div className="space-y-2 pt-2">
            {[
              "Jurisdiction-compliant legal content",
              "Custom branded design with your colors + logo",
              "Desktop + mobile preview",
              "Downloadable ZIP ready for deployment",
            ].map((item) => (
              <div key={item} className="flex items-center gap-2 text-[11px] text-muted-foreground">
                <Check className="h-3 w-3 shrink-0 text-primary" />
                <span>{item}</span>
              </div>
            ))}
          </div>

          {/* CTA row */}
          <div className="flex items-center justify-between border-t border-primary/20 pt-4">
            <span className="text-xs text-muted-foreground">Open Landing Page Generator</span>
            <ArrowRight className="h-4 w-4 text-primary transition-transform group-hover:translate-x-1" />
          </div>
        </div>
      </div>
    </Link>
  );
}
