/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyOnboardingRouteImport } from './routes/my-onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingClientIdRouteImport } from './routes/onboarding.$clientId'
import { Route as OnboardingClientIdIndexRouteImport } from './routes/onboarding.$clientId.index'
import { Route as OnboardingClientIdSuccessRouteImport } from './routes/onboarding.$clientId.success'
import { Route as OnboardingClientIdFormRouteImport } from './routes/onboarding.$clientId.form'
import { Route as OnboardingClientIdAuthRouteImport } from './routes/onboarding.$clientId.auth'

const MyOnboardingRoute = MyOnboardingRouteImport.update({
  id: '/my-onboarding',
  path: '/my-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingClientIdRoute = OnboardingClientIdRouteImport.update({
  id: '/onboarding/$clientId',
  path: '/onboarding/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingClientIdIndexRoute = OnboardingClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingClientIdRoute,
} as any)
const OnboardingClientIdSuccessRoute =
  OnboardingClientIdSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => OnboardingClientIdRoute,
  } as any)
const OnboardingClientIdFormRoute = OnboardingClientIdFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => OnboardingClientIdRoute,
} as any)
const OnboardingClientIdAuthRoute = OnboardingClientIdAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => OnboardingClientIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-onboarding': typeof MyOnboardingRoute
  '/onboarding/$clientId': typeof OnboardingClientIdRouteWithChildren
  '/onboarding/$clientId/auth': typeof OnboardingClientIdAuthRoute
  '/onboarding/$clientId/form': typeof OnboardingClientIdFormRoute
  '/onboarding/$clientId/success': typeof OnboardingClientIdSuccessRoute
  '/onboarding/$clientId/': typeof OnboardingClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-onboarding': typeof MyOnboardingRoute
  '/onboarding/$clientId/auth': typeof OnboardingClientIdAuthRoute
  '/onboarding/$clientId/form': typeof OnboardingClientIdFormRoute
  '/onboarding/$clientId/success': typeof OnboardingClientIdSuccessRoute
  '/onboarding/$clientId': typeof OnboardingClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-onboarding': typeof MyOnboardingRoute
  '/onboarding/$clientId': typeof OnboardingClientIdRouteWithChildren
  '/onboarding/$clientId/auth': typeof OnboardingClientIdAuthRoute
  '/onboarding/$clientId/form': typeof OnboardingClientIdFormRoute
  '/onboarding/$clientId/success': typeof OnboardingClientIdSuccessRoute
  '/onboarding/$clientId/': typeof OnboardingClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/my-onboarding'
    | '/onboarding/$clientId'
    | '/onboarding/$clientId/auth'
    | '/onboarding/$clientId/form'
    | '/onboarding/$clientId/success'
    | '/onboarding/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/my-onboarding'
    | '/onboarding/$clientId/auth'
    | '/onboarding/$clientId/form'
    | '/onboarding/$clientId/success'
    | '/onboarding/$clientId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/my-onboarding'
    | '/onboarding/$clientId'
    | '/onboarding/$clientId/auth'
    | '/onboarding/$clientId/form'
    | '/onboarding/$clientId/success'
    | '/onboarding/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyOnboardingRoute: typeof MyOnboardingRoute
  OnboardingClientIdRoute: typeof OnboardingClientIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-onboarding': {
      id: '/my-onboarding'
      path: '/my-onboarding'
      fullPath: '/my-onboarding'
      preLoaderRoute: typeof MyOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$clientId': {
      id: '/onboarding/$clientId'
      path: '/onboarding/$clientId'
      fullPath: '/onboarding/$clientId'
      preLoaderRoute: typeof OnboardingClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$clientId/': {
      id: '/onboarding/$clientId/'
      path: '/'
      fullPath: '/onboarding/$clientId/'
      preLoaderRoute: typeof OnboardingClientIdIndexRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
    '/onboarding/$clientId/success': {
      id: '/onboarding/$clientId/success'
      path: '/success'
      fullPath: '/onboarding/$clientId/success'
      preLoaderRoute: typeof OnboardingClientIdSuccessRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
    '/onboarding/$clientId/form': {
      id: '/onboarding/$clientId/form'
      path: '/form'
      fullPath: '/onboarding/$clientId/form'
      preLoaderRoute: typeof OnboardingClientIdFormRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
    '/onboarding/$clientId/auth': {
      id: '/onboarding/$clientId/auth'
      path: '/auth'
      fullPath: '/onboarding/$clientId/auth'
      preLoaderRoute: typeof OnboardingClientIdAuthRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
  }
}

interface OnboardingClientIdRouteChildren {
  OnboardingClientIdAuthRoute: typeof OnboardingClientIdAuthRoute
  OnboardingClientIdFormRoute: typeof OnboardingClientIdFormRoute
  OnboardingClientIdSuccessRoute: typeof OnboardingClientIdSuccessRoute
  OnboardingClientIdIndexRoute: typeof OnboardingClientIdIndexRoute
}

const OnboardingClientIdRouteChildren: OnboardingClientIdRouteChildren = {
  OnboardingClientIdAuthRoute: OnboardingClientIdAuthRoute,
  OnboardingClientIdFormRoute: OnboardingClientIdFormRoute,
  OnboardingClientIdSuccessRoute: OnboardingClientIdSuccessRoute,
  OnboardingClientIdIndexRoute: OnboardingClientIdIndexRoute,
}

const OnboardingClientIdRouteWithChildren =
  OnboardingClientIdRoute._addFileChildren(OnboardingClientIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyOnboardingRoute: MyOnboardingRoute,
  OnboardingClientIdRoute: OnboardingClientIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
