/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyOnboardingRouteImport } from './routes/my-onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioPreviewClientIdRouteImport } from './routes/studio-preview.$clientId'
import { Route as ProspectTokenRouteImport } from './routes/prospect.$token'
import { Route as OnboardingClientIdRouteImport } from './routes/onboarding.$clientId'
import { Route as OnboardingClientIdIndexRouteImport } from './routes/onboarding.$clientId.index'
import { Route as ProspectWelcomeTokenRouteImport } from './routes/prospect_.welcome.$token'
import { Route as OnboardingClientIdSuccessRouteImport } from './routes/onboarding.$clientId.success'
import { Route as OnboardingClientIdStudioUnlockedRouteImport } from './routes/onboarding.$clientId.studio-unlocked'
import { Route as OnboardingClientIdStudioPreviewRouteImport } from './routes/onboarding.$clientId.studio-preview'
import { Route as OnboardingClientIdStudioLockedRouteImport } from './routes/onboarding.$clientId.studio-locked'
import { Route as OnboardingClientIdStudioIntroRouteImport } from './routes/onboarding.$clientId.studio-intro'
import { Route as OnboardingClientIdStudioRouteImport } from './routes/onboarding.$clientId.studio'
import { Route as OnboardingClientIdFormRouteImport } from './routes/onboarding.$clientId.form'
import { Route as OnboardingClientIdAuthRouteImport } from './routes/onboarding.$clientId.auth'
import { Route as AdminProspectsIdEditRouteImport } from './routes/admin.prospects.$id.edit'

const MyOnboardingRoute = MyOnboardingRouteImport.update({
  id: '/my-onboarding',
  path: '/my-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPreviewClientIdRoute = StudioPreviewClientIdRouteImport.update({
  id: '/studio-preview/$clientId',
  path: '/studio-preview/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectTokenRoute = ProspectTokenRouteImport.update({
  id: '/prospect/$token',
  path: '/prospect/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingClientIdRoute = OnboardingClientIdRouteImport.update({
  id: '/onboarding/$clientId',
  path: '/onboarding/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingClientIdIndexRoute = OnboardingClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingClientIdRoute,
} as any)
const ProspectWelcomeTokenRoute = ProspectWelcomeTokenRouteImport.update({
  id: '/prospect_/welcome/$token',
  path: '/prospect/welcome/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingClientIdSuccessRoute =
  OnboardingClientIdSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => OnboardingClientIdRoute,
  } as any)
const OnboardingClientIdStudioUnlockedRoute =
  OnboardingClientIdStudioUnlockedRouteImport.update({
    id: '/studio-unlocked',
    path: '/studio-unlocked',
    getParentRoute: () => OnboardingClientIdRoute,
  } as any)
const OnboardingClientIdStudioPreviewRoute =
  OnboardingClientIdStudioPreviewRouteImport.update({
    id: '/studio-preview',
    path: '/studio-preview',
    getParentRoute: () => OnboardingClientIdRoute,
  } as any)
const OnboardingClientIdStudioLockedRoute =
  OnboardingClientIdStudioLockedRouteImport.update({
    id: '/studio-locked',
    path: '/studio-locked',
    getParentRoute: () => OnboardingClientIdRoute,
  } as any)
const OnboardingClientIdStudioIntroRoute =
  OnboardingClientIdStudioIntroRouteImport.update({
    id: '/studio-intro',
    path: '/studio-intro',
    getParentRoute: () => OnboardingClientIdRoute,
  } as any)
const OnboardingClientIdStudioRoute =
  OnboardingClientIdStudioRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => OnboardingClientIdRoute,
  } as any)
const OnboardingClientIdFormRoute = OnboardingClientIdFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => OnboardingClientIdRoute,
} as any)
const OnboardingClientIdAuthRoute = OnboardingClientIdAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => OnboardingClientIdRoute,
} as any)
const AdminProspectsIdEditRoute = AdminProspectsIdEditRouteImport.update({
  id: '/prospects/$id/edit',
  path: '/prospects/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-onboarding': typeof MyOnboardingRoute
  '/onboarding/$clientId': typeof OnboardingClientIdRouteWithChildren
  '/prospect/$token': typeof ProspectTokenRoute
  '/studio-preview/$clientId': typeof StudioPreviewClientIdRoute
  '/onboarding/$clientId/auth': typeof OnboardingClientIdAuthRoute
  '/onboarding/$clientId/form': typeof OnboardingClientIdFormRoute
  '/onboarding/$clientId/studio': typeof OnboardingClientIdStudioRoute
  '/onboarding/$clientId/studio-intro': typeof OnboardingClientIdStudioIntroRoute
  '/onboarding/$clientId/studio-locked': typeof OnboardingClientIdStudioLockedRoute
  '/onboarding/$clientId/studio-preview': typeof OnboardingClientIdStudioPreviewRoute
  '/onboarding/$clientId/studio-unlocked': typeof OnboardingClientIdStudioUnlockedRoute
  '/onboarding/$clientId/success': typeof OnboardingClientIdSuccessRoute
  '/prospect/welcome/$token': typeof ProspectWelcomeTokenRoute
  '/onboarding/$clientId/': typeof OnboardingClientIdIndexRoute
  '/admin/prospects/$id/edit': typeof AdminProspectsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-onboarding': typeof MyOnboardingRoute
  '/prospect/$token': typeof ProspectTokenRoute
  '/studio-preview/$clientId': typeof StudioPreviewClientIdRoute
  '/onboarding/$clientId/auth': typeof OnboardingClientIdAuthRoute
  '/onboarding/$clientId/form': typeof OnboardingClientIdFormRoute
  '/onboarding/$clientId/studio': typeof OnboardingClientIdStudioRoute
  '/onboarding/$clientId/studio-intro': typeof OnboardingClientIdStudioIntroRoute
  '/onboarding/$clientId/studio-locked': typeof OnboardingClientIdStudioLockedRoute
  '/onboarding/$clientId/studio-preview': typeof OnboardingClientIdStudioPreviewRoute
  '/onboarding/$clientId/studio-unlocked': typeof OnboardingClientIdStudioUnlockedRoute
  '/onboarding/$clientId/success': typeof OnboardingClientIdSuccessRoute
  '/prospect/welcome/$token': typeof ProspectWelcomeTokenRoute
  '/onboarding/$clientId': typeof OnboardingClientIdIndexRoute
  '/admin/prospects/$id/edit': typeof AdminProspectsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-onboarding': typeof MyOnboardingRoute
  '/onboarding/$clientId': typeof OnboardingClientIdRouteWithChildren
  '/prospect/$token': typeof ProspectTokenRoute
  '/studio-preview/$clientId': typeof StudioPreviewClientIdRoute
  '/onboarding/$clientId/auth': typeof OnboardingClientIdAuthRoute
  '/onboarding/$clientId/form': typeof OnboardingClientIdFormRoute
  '/onboarding/$clientId/studio': typeof OnboardingClientIdStudioRoute
  '/onboarding/$clientId/studio-intro': typeof OnboardingClientIdStudioIntroRoute
  '/onboarding/$clientId/studio-locked': typeof OnboardingClientIdStudioLockedRoute
  '/onboarding/$clientId/studio-preview': typeof OnboardingClientIdStudioPreviewRoute
  '/onboarding/$clientId/studio-unlocked': typeof OnboardingClientIdStudioUnlockedRoute
  '/onboarding/$clientId/success': typeof OnboardingClientIdSuccessRoute
  '/prospect_/welcome/$token': typeof ProspectWelcomeTokenRoute
  '/onboarding/$clientId/': typeof OnboardingClientIdIndexRoute
  '/admin/prospects/$id/edit': typeof AdminProspectsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/my-onboarding'
    | '/onboarding/$clientId'
    | '/prospect/$token'
    | '/studio-preview/$clientId'
    | '/onboarding/$clientId/auth'
    | '/onboarding/$clientId/form'
    | '/onboarding/$clientId/studio'
    | '/onboarding/$clientId/studio-intro'
    | '/onboarding/$clientId/studio-locked'
    | '/onboarding/$clientId/studio-preview'
    | '/onboarding/$clientId/studio-unlocked'
    | '/onboarding/$clientId/success'
    | '/prospect/welcome/$token'
    | '/onboarding/$clientId/'
    | '/admin/prospects/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/my-onboarding'
    | '/prospect/$token'
    | '/studio-preview/$clientId'
    | '/onboarding/$clientId/auth'
    | '/onboarding/$clientId/form'
    | '/onboarding/$clientId/studio'
    | '/onboarding/$clientId/studio-intro'
    | '/onboarding/$clientId/studio-locked'
    | '/onboarding/$clientId/studio-preview'
    | '/onboarding/$clientId/studio-unlocked'
    | '/onboarding/$clientId/success'
    | '/prospect/welcome/$token'
    | '/onboarding/$clientId'
    | '/admin/prospects/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/my-onboarding'
    | '/onboarding/$clientId'
    | '/prospect/$token'
    | '/studio-preview/$clientId'
    | '/onboarding/$clientId/auth'
    | '/onboarding/$clientId/form'
    | '/onboarding/$clientId/studio'
    | '/onboarding/$clientId/studio-intro'
    | '/onboarding/$clientId/studio-locked'
    | '/onboarding/$clientId/studio-preview'
    | '/onboarding/$clientId/studio-unlocked'
    | '/onboarding/$clientId/success'
    | '/prospect_/welcome/$token'
    | '/onboarding/$clientId/'
    | '/admin/prospects/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyOnboardingRoute: typeof MyOnboardingRoute
  OnboardingClientIdRoute: typeof OnboardingClientIdRouteWithChildren
  ProspectTokenRoute: typeof ProspectTokenRoute
  StudioPreviewClientIdRoute: typeof StudioPreviewClientIdRoute
  ProspectWelcomeTokenRoute: typeof ProspectWelcomeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-onboarding': {
      id: '/my-onboarding'
      path: '/my-onboarding'
      fullPath: '/my-onboarding'
      preLoaderRoute: typeof MyOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-preview/$clientId': {
      id: '/studio-preview/$clientId'
      path: '/studio-preview/$clientId'
      fullPath: '/studio-preview/$clientId'
      preLoaderRoute: typeof StudioPreviewClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospect/$token': {
      id: '/prospect/$token'
      path: '/prospect/$token'
      fullPath: '/prospect/$token'
      preLoaderRoute: typeof ProspectTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$clientId': {
      id: '/onboarding/$clientId'
      path: '/onboarding/$clientId'
      fullPath: '/onboarding/$clientId'
      preLoaderRoute: typeof OnboardingClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$clientId/': {
      id: '/onboarding/$clientId/'
      path: '/'
      fullPath: '/onboarding/$clientId/'
      preLoaderRoute: typeof OnboardingClientIdIndexRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
    '/prospect_/welcome/$token': {
      id: '/prospect_/welcome/$token'
      path: '/prospect/welcome/$token'
      fullPath: '/prospect/welcome/$token'
      preLoaderRoute: typeof ProspectWelcomeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$clientId/success': {
      id: '/onboarding/$clientId/success'
      path: '/success'
      fullPath: '/onboarding/$clientId/success'
      preLoaderRoute: typeof OnboardingClientIdSuccessRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
    '/onboarding/$clientId/studio-unlocked': {
      id: '/onboarding/$clientId/studio-unlocked'
      path: '/studio-unlocked'
      fullPath: '/onboarding/$clientId/studio-unlocked'
      preLoaderRoute: typeof OnboardingClientIdStudioUnlockedRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
    '/onboarding/$clientId/studio-preview': {
      id: '/onboarding/$clientId/studio-preview'
      path: '/studio-preview'
      fullPath: '/onboarding/$clientId/studio-preview'
      preLoaderRoute: typeof OnboardingClientIdStudioPreviewRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
    '/onboarding/$clientId/studio-locked': {
      id: '/onboarding/$clientId/studio-locked'
      path: '/studio-locked'
      fullPath: '/onboarding/$clientId/studio-locked'
      preLoaderRoute: typeof OnboardingClientIdStudioLockedRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
    '/onboarding/$clientId/studio-intro': {
      id: '/onboarding/$clientId/studio-intro'
      path: '/studio-intro'
      fullPath: '/onboarding/$clientId/studio-intro'
      preLoaderRoute: typeof OnboardingClientIdStudioIntroRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
    '/onboarding/$clientId/studio': {
      id: '/onboarding/$clientId/studio'
      path: '/studio'
      fullPath: '/onboarding/$clientId/studio'
      preLoaderRoute: typeof OnboardingClientIdStudioRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
    '/onboarding/$clientId/form': {
      id: '/onboarding/$clientId/form'
      path: '/form'
      fullPath: '/onboarding/$clientId/form'
      preLoaderRoute: typeof OnboardingClientIdFormRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
    '/onboarding/$clientId/auth': {
      id: '/onboarding/$clientId/auth'
      path: '/auth'
      fullPath: '/onboarding/$clientId/auth'
      preLoaderRoute: typeof OnboardingClientIdAuthRouteImport
      parentRoute: typeof OnboardingClientIdRoute
    }
    '/admin/prospects/$id/edit': {
      id: '/admin/prospects/$id/edit'
      path: '/prospects/$id/edit'
      fullPath: '/admin/prospects/$id/edit'
      preLoaderRoute: typeof AdminProspectsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminProspectsIdEditRoute: typeof AdminProspectsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProspectsIdEditRoute: AdminProspectsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OnboardingClientIdRouteChildren {
  OnboardingClientIdAuthRoute: typeof OnboardingClientIdAuthRoute
  OnboardingClientIdFormRoute: typeof OnboardingClientIdFormRoute
  OnboardingClientIdStudioRoute: typeof OnboardingClientIdStudioRoute
  OnboardingClientIdStudioIntroRoute: typeof OnboardingClientIdStudioIntroRoute
  OnboardingClientIdStudioLockedRoute: typeof OnboardingClientIdStudioLockedRoute
  OnboardingClientIdStudioPreviewRoute: typeof OnboardingClientIdStudioPreviewRoute
  OnboardingClientIdStudioUnlockedRoute: typeof OnboardingClientIdStudioUnlockedRoute
  OnboardingClientIdSuccessRoute: typeof OnboardingClientIdSuccessRoute
  OnboardingClientIdIndexRoute: typeof OnboardingClientIdIndexRoute
}

const OnboardingClientIdRouteChildren: OnboardingClientIdRouteChildren = {
  OnboardingClientIdAuthRoute: OnboardingClientIdAuthRoute,
  OnboardingClientIdFormRoute: OnboardingClientIdFormRoute,
  OnboardingClientIdStudioRoute: OnboardingClientIdStudioRoute,
  OnboardingClientIdStudioIntroRoute: OnboardingClientIdStudioIntroRoute,
  OnboardingClientIdStudioLockedRoute: OnboardingClientIdStudioLockedRoute,
  OnboardingClientIdStudioPreviewRoute: OnboardingClientIdStudioPreviewRoute,
  OnboardingClientIdStudioUnlockedRoute: OnboardingClientIdStudioUnlockedRoute,
  OnboardingClientIdSuccessRoute: OnboardingClientIdSuccessRoute,
  OnboardingClientIdIndexRoute: OnboardingClientIdIndexRoute,
}

const OnboardingClientIdRouteWithChildren =
  OnboardingClientIdRoute._addFileChildren(OnboardingClientIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyOnboardingRoute: MyOnboardingRoute,
  OnboardingClientIdRoute: OnboardingClientIdRouteWithChildren,
  ProspectTokenRoute: ProspectTokenRoute,
  StudioPreviewClientIdRoute: StudioPreviewClientIdRoute,
  ProspectWelcomeTokenRoute: ProspectWelcomeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
